<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6L2v5Lu2L+aPkuS7tg==');
$cfg_Cs[2]=array(0,1,1,'5pWZ56iL');
$cfg_Cs[3]=array(1,1,1,'M0Tova/ku7Y=');
$cfg_Cs[4]=array(1,1,1,'MkTova/ku7Y=');
$cfg_Cs[5]=array(2,1,1,'M0TmlZnnqIs=');
$cfg_Cs[10]=array(3,1,1,'M2QtMQ==');
$cfg_Cs[11]=array(3,1,1,'M2QtMg==');
$cfg_Cs[9]=array(2,1,1,'MkTmlZnnqIs=');
$cfg_Cs[12]=array(5,1,1,'amMtMQ==');
?>