<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'5pWZ56iL');
$cfg_Cs[14]=array(13,1,1,'6L2v5Lu2');
$cfg_Cs[5]=array(2,1,1,'M0TmlZnnqIs=');
$cfg_Cs[18]=array(13,1,1,'5o+S5Lu2');
$cfg_Cs[9]=array(2,1,1,'MkTmlZnnqIs=');
$cfg_Cs[13]=array(0,1,1,'6L2v5Lu2L+aPkuS7tg==');
$cfg_Cs[21]=array(0,1,1,'6LS05Zu+');
$cfg_Cs[22]=array(21,1,1,'5pyo5p2Q');
$cfg_Cs[58]=array(60,1,1,'QU0=');
$cfg_Cs[60]=array(0,1,0,'5qih5Z6L');
?>