<?php
$z[0]=Array("arcurl","",69,84);
$z[1]=Array("litpic","",110,125);
$z[2]=Array("description","",221,242);
$z[3]=Array("arcurl","",342,357);
$z[4]=Array("title","",359,374);
$z[5]=Array("id","     \r\nglobal \$cfg_cmspath;        \r\n\$tags = GetTags(@me);        \r\n\$revalue = '';        \r\n\$tags = explode(',', \$tags);        \r\nforeach(\$tags as \$key => \$value){\r\n            if(\$value){\r\n                \$revalue .= '<a href=\"'.\$cfg_cmspath.'/tags.php?/'.\$value.'/\">'.\$value.'</a> ';         \r\n   }      \r\n  }        \r\n@me = \$revalue;     \r\n",676,1053);
$z[5][4]['runphp']="yes";
$z[6]=Array("click","",1202,1217);
$z[7]=Array("id","",1284,1316);
$z[7][4]['function']="cnum(@me)";
$z[8]=Array("id","",1396,1427);
$z[8][4]['function']="zan(@me)";

?>