<?php
$z[0]=Array("type","\n    	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"98%\">\n    		<tr>\n    		<td width='10%'><img src='[field:global name='cfg_templeturl'/]/img/channellist.gif' width='14' height='16'></td>\n    	 <td width='60%'>\n    	<a href=\"[field:typelink /]\">[field:typename /]</a>\n        </td>\n      <td width='30%' align='right'>\n      <a href=\"[field:typelink /]\">更多...</a>\n      </td>\n    </tr>\n   </table>\n   ",120,560);
$z[1]=Array("arclist","\n	·<a href=\"[field:arcurl /]\">[field:title /]</a><br>\n  ",639,725);

?>