<div class="cginew">
            <div class="tit clearfix">
            <h2>[field:typename/]</h2>
            <a href="#">查看更多</a>
          </div>

          


          <div class="layui-tab-item">
          <div class="layui-row">
              <div class="border">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img.jpg" /><span class="new">最新</span>
                <div class="shadow" style="display:none;"> 犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具之一。犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href="#">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
              </div>
              <div class="border">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img2.jpg" /><span class="new">最新</span>
                <div class="shadow" style="display:none;"> 犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具之一。犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href="#">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
              </div>
              <div class="border">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img3.jpg" /><span class="new">最新</span>
                <div class="shadow" style="display:none;"> 犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具之一。犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href="#">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
              </div>
              <div class="border">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img4.jpg" /><span class="new">最新</span>
                <div class="shadow" style="display:none;"> 犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具之一。犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href="#">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
              </div>
              <div class="border">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img5.jpg" /><span class="new">最新</span>
                <div class="shadow" style="display:none;"> 犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具之一。犀牛的V-Ray 提供了可视化的最先进的解渲云渲染，让渲染更高效。犀牛是当今最流行的基于Windows的NURBS建模工具 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href="#">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
              </div>
          </div>
        </div>
      </div>