<?php
$z[0]=Array("arcurl","",69,84);
$z[1]=Array("litpic","",110,125);
$z[2]=Array("description","",221,242);
$z[3]=Array("arcurl","",342,357);
$z[4]=Array("title","",359,374);
$z[5]=Array("tag","",719,732);
$z[6]=Array("tag","",734,747);
$z[7]=Array("click","",879,894);
$z[8]=Array("id","",961,993);
$z[8][4]['function']="cnum(@me)";
$z[9]=Array("id","",1073,1104);
$z[9][4]['function']="zan(@me)";

?>