<div class="border">
              <div class="grid-demo"> <a href=" /ruanjianchajian/ruanjianyi/ruanjian1/2019-05-15/88.html" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img.jpg" />
                <div class="shadow" style="display:none;"> Lynda - Learning Algorithmic Design with GrasshopperLynda - 学习犀牛里的Grasshopper算法教程 </div>
                </a>
                <div class="cgiarc">
                  <h3><a href=" /ruanjianchajian/ruanjianyi/ruanjian1/2019-05-15/88.html ">测试文章２</a></h3>
                  <div class="tag"><strong><a href="#" target="_blank">超写实</a> <a href="#" target="_blank">模型</a> <a href="#" target="_blank">预售</a> <a href="#" target="_blank">场景</a> </li></strong></div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i><script src=/e/public/ViewClick/?classid=9&id=88></script></span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>1</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i><script src=/e/public/ViewClick/?classid=9&id=88&down=5></script></span></div>
                </div>
              </div>
        </div>