
      <li class="layui-nav-item"> <a href="javascript:;">[field:typename/]</a> <dl class="layui-nav-child snav">
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          
        </dl></li>
      