

        <li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a> 
    <ul> 
    {dede:sql sql='Select * from dede_arctype where reid=~id~'} 
    <li><a href='[field:typedir function='str_replace("{cmspath}","",@me)'/]'>[field:typename/]</a></li> 
    {/dede:sql}//开源软件:phpfensi.com 
    </ul> 
    </li> 

        <!-- <li class="layui-nav-item"> <a href="">软件/插件</a> <dl class="layui-nav-child snav">
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          <dd>
          <a href="javascript:;" class="btit">3D资源</a>
          <div class="snavfl clearfix"><a href="#">建筑室建内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建建建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a><a href="#">建筑室内</a></div>
          </dd>
          
        </dl></li> -->
      