<table border="0" cellpadding="0" cellspacing="0" width="98%">
    		<tr>
    		<td width='10%'><img src='[field:global name='cfg_templeturl'/]/img/channellist.gif' width='14' height='16'></td>
    	 <td width='60%'>
    	<a href="[field:typelink /]">[field:typename /]</a>
        </td>
      <td width='30%' align='right'>
      <a href="[field:typelink /]">更多...</a>
      </td>
    </tr>
   </table>