<div class="layui-col-xs3">
              <div class="grid-demo"> <a href="#" class="show"> <img src="{dede:global.cfg_templets_skin/}/images/img1.jpg" />
</a>
                <div class="cgiarc">
                  <div class="cgiarc1">
                  <h3><a href="#" title="渲云渲染，让渲染更高效">渲云渲染，让渲染更高效</a></h3>
                  <div class="tag"><strong><a href="#">插画</a></strong><strong><a href="#">手绘</a></strong><strong><a href="#">绘画</a></strong><strong><a href="#">教程</a></strong><strong><a href="#">场景</a></strong><strong><a href="#">全景</a></strong></div>
                  <div class="tag tag1"><strong>标签</strong><strong>标签</strong><strong>标签</strong><strong>标签</strong><strong>标签</strong></div>
                  </div>
                  <div class="action"> <span><i class="fa fa-eye" aria-hidden="true"></i>66</span><span><i class="fa fa-commenting-o" aria-hidden="true"></i>12</span><span class="handok"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i>24</span></div>
                </div>
              </div>
            </div>