<li>[<b>[field:typelink/]</b>]<a href="[field:arcurl/]" >[field:title/]</a></li>

             <li class="clearfix">
             <img src="{dede:global.cfg_templets_skin/}/images/shiwan/pic3.jpg">
             <div>
                <h2>钱坊<span></span></h2>
<p>钱坊APP让你随时赚不停的苹果新平台，下载试玩APP应用就能获得现金奖励。每天大量任务，提现门门槛超低，2元就能提现，你
的朋友都在用这个赚钱</p>
<h3><span>大小： 5.6M</span><span>支持固件：苹果</span><span>下载次数：666</span></h3>

</div>
<a href="[field:arcurl/]">点击下载</a>
             </li>